# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: mysql
    restart: always
    ports:
      - 3388:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: padariaecoxinha
    # (this is just an example, not intended to be a production configuration)
